dist: xenial
language: python
python: '3.7'

env:
  global:
    - COLLECTION_NAMESPACE: lvrfrc87
    - COLLECTION_NAME: git_acp
  matrix:
  - ANSIBLE_VERSION=2.9.5
  - ANSIBLE_VERSION=latets

branches:
  only:
  - master
  - dev

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi

before_install:
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  - ansible-test sanity -v --color --test pep8
  - ansible-playbook tests/integration/targets/source_control/git_acp.yaml -vvv
