dist: xenial
language: python
python: '3.7'
env:
  matrix:
  # - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.9.5
  global:
  - secure: lXuBHBAHHoMg8jpCUMhBi6rH7CER5vSkFIUAQA9raYMOHXLCEtVNtHen9rTRFKyl0BlvGwSbRR35XAoTG/yGSlMb17y/GDz98HiY/QYth1Kof0YNh+vrIJBQt3dACQNGorTMUB4WfCV+lMRh6bNw/bAWO1b3YmJ2kRIMvg+fLDZzpy3v6tYKP2Kj0I9JJvyLK9Cae7Ic2hDI8QFeGSAgDc9qLwY5y4X7Eu+zuGWLoIi+E8yQslmHfCBSSKadohux5tq05ErkfBkgjuPy9kYmS+zepvLwRgjYMtA78Esddq4jnKawqVD2O252SQjEAc0MtR66NIKuccO3MhSXEFbjVIi8S2vwaB4/HelMg1Gme2IUEVBG5AS8hr0XiXshhgNPZcBQ2jcFYmesPTjgRg8nnLrqXZue3VoI0gzC0EQYJwpG2haulZfT5l5w+Y+F/F1JqzI4WKn30pySr8tvmzTTu+z3/bZVUyXVLPBEwTV/4cZFaOJPzh/gp0D2e409ByO90GnqmGkkI7jvJtMSGxyiwI+NjKo0CKUPpkg7P7oyuGFWW+6nKBTgZYMz0Zbz6vSbCl3IxMQFy6s32MAT3YNRgI711Nt2OPrJprPPZmCkVTi532DeNjbQrpywhIKNfJJw88FnoU6qVs6BzFRG2PEFN0SGtZvBLE8RO52CHXwMh9w=
  - secure: I+B0j35VPQqdHC8gRH44xJA9DbcsYPqU7cL8YW0KeYulgtZMZ4Uz/9sv9ZJ6GblzqWJXIHcJb50vJj1Gq/UCzrswkbfjJuw03/333cEqN4Zf3lhBxexyhVwH089EW6Qp59GJeNlR8njxjLzX4RF5Z2L4ROUeKx/O7NVthzVIBe2A+SHOvOVvdgTNALneJzx9aPcmUqR9WiKcG0mCt+sQS89OD92+ucAJUKjH8JJ1BsdWnq0LQfhFw9TNctjolCZIlwO90ec6NOerbl+i0bYEOuZ1jUeYo6OURK/RGkYWaNaEzvb/7BnvEf5KF/B8yRZQ/rgjgAV+AboU3QXHGqKKZBwz4dq8jlc2KgYpAYwBSeKhMNnYxSr/qfsG4eU/Z4BCVJjj+ZCREHG8svUBDpi22WMklwXfj1+zXxle6m/03P5rnj1XITRV7Dljr2gTZiPdBzJZW+/E8T2XPYk0TmNFagjUBIixfnOnVwpv6pF5gsms61Zgx+erdC/KWlr82grsxr92OYCeiGH9B8iQhuoOrkUp5KyclRbVnee33qtDMnJdSeLzjpngjOJi+u6rNFUID9kXBrnCVKFtrXkDgloxdAq1lxcuY8Yk9t2wLTdET9eE5xoO3pKx9x8ahFV/skNxPSo37MXqsqmw1MY2qhCK2sIAUYUBk1XI0WrR4/flSC4=
branches:
  only:
  - master
  - dev
before_install:
- sudo apt-get update -qq
install:
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
script:
- ansible-playbook tests/integration/targets/source_control/git_acp.yaml -vv
