dist: xenial
language: python
python: '3.7'
env:
  matrix:
  - ANSIBLE_VERSION=2.9.5
branches:
  only:
  - master
  - dev
before_install:
- sudo apt-get update -qq
install:
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
- pip install ansible-lint
script:
- ansible-lint -x 502,305,301,303,401,208 tests/integration/targets/source_control/git_acp.yaml
- ansible-playbook tests/integration/targets/source_control/git_acp.yaml -vvv
