dist: xenial
language: python
python: '3.7'
env:
  matrix:
  - ANSIBLE_VERSION=2.9.5
  global:
  - secure: H3V/GNYQpe88RLz54qjMEc6cOZ6StYMZAvdt0aOvAkJckMoVlAPjr+vQ54dB2yp1wAfGeAdV2M2Tf0L1bjcXOKG8+AeCK0qSJOiHSVcWECV8jcP8qCkBrYe4Jnt14L4K7Y7fHBhrJFm6PrNRtxbt5z04ybS6Sf0t/j6THw8wMFIYaEIl9OSniIHtew130z29pj1oy7X/T0HJqbri0+E0qaGjJVT9CmG21864vjoCrH29L3lDyV2ZiyTeIniNELn1vWhvsesz/8DjvkNeiiAiUJCrN5zl+fW3vdbngpophPJMq+a26AhJKRrROIE6LbUJGUjU+NiKJDKvKuAZXeflMWKCC3FI9V9hf7wTn6+5bBNtTmqlJkwXFtFA88vzAlNGlkvg1ZTVrYTI5qnyUYcNeRbJsEt/TmaLQ3oy6dQ6l1ViFy7wFKps03etFsOdnoBDjyVG+rrNQSCBHfoQQSE4oAXxKpNFnyLyRaRwEJVaYLmtecANKpwrLCwzL6CHIXLNPLiCXq1Whtx8UD5XlpCN+CZt7n1SJhPomrfuMZcd2ZoWtdbegOQRwTKmDCHk9V9PGSisbyGtVMgJjY6DHC4EqnwZu9zTC8tk3z2TbIqMQ2hW7Blt3tGdofVJ9rpRKg9JvXDsE1vZa46weGbsQCm4fxNAMHPex8gfTK7bPzs5A/E=
branches:
  only:
  - master
  - dev
before_install:
- sudo apt-get update -qq
install:
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
script:
- ansible-playbook tests/integration/targets/source_control/git_acp.yaml -vvv
