dist: xenial
language: python
python: '3.7'
env:
  matrix:
  - ANSIBLE_VERSION=2.9.5
  global:
  - secure: cA4b/WAp0BXh07t0umZ0sKWTJ7qX7i4G8lrPVwYm8oaWjfbY2lCp6BqrpYRL76Sf0kAS8poC7yTteUF4xwJZsfTwFfR7nnjlR1w3ENv2AE92EfkrOHjG97kQjJau3rrLTTNnrIGrOcB2E4b4tjLzA8FAglfE9b63iiEWa947pN0Uin89EnAQBHJCv5w8q+HTfh6JqiuGWnnLQ+RYsK0XDcQN/nw5BN1jB0EpVp+FAF7ra+y44zkzCy4VDT0Mb3xemR8diHPbl42HJGYqLi2xMnkrMLrJDtIg868HihhT2j0b9jUZbawzNDRU9Gj6QLMfNicsNe9T/EXq39n/Styep5WpCBcFZyN/3FLcsp7GQP9FroFsU8jwtrGSnXs9pElFGMPM6UN4LFRSRnXfF00JFpqiHEsfT5eSmZ06Tvd/KwGlOk9bCQRfyzAiKTHRXnzDSCQXbkRLzmbqmKRHppVFkctyQZDzg3KC9pNWZo3hm2Z+AEh4j2ZG7jJjmxSMetf7YplX4qEQUE7PrZG+Gl0U/+DQu5GXYE6aMo9n+GBWDBaMJXRcEp6zL5LQZ7QCo3quyZDVjN4LfaZ+x0FmDfmF1TNWIAkkWAXz+noVzqXaVxuF9na/TkjGXsQE1VZdWM4JN//QBmOPyNo7fnh8kMFV4Cwvp4M0ad0V+X7bEXHpJQE=
  - secure: H3V/GNYQpe88RLz54qjMEc6cOZ6StYMZAvdt0aOvAkJckMoVlAPjr+vQ54dB2yp1wAfGeAdV2M2Tf0L1bjcXOKG8+AeCK0qSJOiHSVcWECV8jcP8qCkBrYe4Jnt14L4K7Y7fHBhrJFm6PrNRtxbt5z04ybS6Sf0t/j6THw8wMFIYaEIl9OSniIHtew130z29pj1oy7X/T0HJqbri0+E0qaGjJVT9CmG21864vjoCrH29L3lDyV2ZiyTeIniNELn1vWhvsesz/8DjvkNeiiAiUJCrN5zl+fW3vdbngpophPJMq+a26AhJKRrROIE6LbUJGUjU+NiKJDKvKuAZXeflMWKCC3FI9V9hf7wTn6+5bBNtTmqlJkwXFtFA88vzAlNGlkvg1ZTVrYTI5qnyUYcNeRbJsEt/TmaLQ3oy6dQ6l1ViFy7wFKps03etFsOdnoBDjyVG+rrNQSCBHfoQQSE4oAXxKpNFnyLyRaRwEJVaYLmtecANKpwrLCwzL6CHIXLNPLiCXq1Whtx8UD5XlpCN+CZt7n1SJhPomrfuMZcd2ZoWtdbegOQRwTKmDCHk9V9PGSisbyGtVMgJjY6DHC4EqnwZu9zTC8tk3z2TbIqMQ2hW7Blt3tGdofVJ9rpRKg9JvXDsE1vZa46weGbsQCm4fxNAMHPex8gfTK7bPzs5A/E=
branches:
  only:
  - master
  - dev
before_install:
- sudo apt-get update -qq
install:
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
script:
- ansible-playbook tests/integration/targets/source_control/git_acp.yaml -vvv
