dist: xenial
language: python
python: '3.7'
env:
  matrix:
  - ANSIBLE_VERSION=2.9.5
  global:
  - secure: Ok0b5xemhQ6bSFL6eu1KXWzmMr8slSFxYqKKVdFLHKrHir0FvsZQn2NMEiIVbE31NJhQQzg3VbF5+9xU1Yvm8kVVi2J+kdsBXKThrhkPWy042PCRuX1CH/QPC37T8MWMqxyaGJJO49E9i9l2pJ2cqwH/tmvRFgIvuCpKs/EvyDKi4VL9pJdcFReM+/9YNFwMJkhRODJjKolpLlENp5mwFTKRm0f66KJbxeV5GpvPqYYd84sWJeYCkBo4YgmmSwE9aDIa6QLapbU5iSQ4oUBpo3Or5hdxl3zQK1mH/VPeWDpz2xWMDvMc0Rw56/aZxZRJc+cjaObcSmbKs8VNbM2zuwR+6hB/3odbpkyIyvI2YFLs1JVWfMqw0DyDuz9es+V8m9a+cl2Cje8mZD3zjsZNOciuk/cAVDxRcpgjrdZgRVp9F9Jx5TbGvr6/OKpvgTYxQGc8zJle5gsLbwGSZJC4HYcLe6+MjLCBIVaVHgHVDPcFhH5SA9Q9FWynW5UJXQQHZDnjkzOBWQCE94Qp13+pOo9ieZfvkCQMWfLCxCNSoR2LXPshoEVL4yjxFDRBlDF4ux+AkofBtb+nhsLEmb1GgvfD7idj/OqJmXWy34K5VJWBhlx2GCWALgKOqz23jYjjw+XxsQ9gotV/2RA56M2NEWA9a6Gwi8fvUu8F6sEVaBM=
branches:
  only:
  - master
  - dev
before_install:
- sudo apt-get update -qq
install:
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
script:
- ansible-playbook tests/integration/targets/source_control/git_acp.yaml -vvv
